"""add request config to load tests

Revision ID: 6937fe93b86c
Revises: 233652591798
Create Date: 2026-06-22 16:07:21.898687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6937fe93b86c'
down_revision: Union[str, None] = '233652591798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('load_tests', sa.Column('http_method', sa.String(length=10), nullable=False))
    op.add_column('load_tests', sa.Column('request_headers', sa.Text(), nullable=True))
    op.add_column('load_tests', sa.Column('request_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('load_tests', 'request_body')
    op.drop_column('load_tests', 'request_headers')
    op.drop_column('load_tests', 'http_method')
    # ### end Alembic commands ###
